### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ClemensGruber** [agent-r/Serial-Plotter#1]
[Enter steps to reproduce:]

1. I used this test sketch on Arduino 
int i = 0;

// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);

}
// the loop routine runs over and over again forever:
void loop() {
  Serial.println(i++);
  if (i>50) i=0;
  delay(10);        // delay in between reads for stability
}

2. Then I went to atom and startet the serial plotter

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: WIN10
**Thrown From**: [serial-plotter](https://github.com/agent-r/Serial-Plotter) package 0.1.8

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\mail\.atom\packages\serial-plotter\lib\serial-plotter.js:134

TypeError: Cannot read property '0' of undefined
    at stdout (/packages/serial-plotter/lib/serial-plotter.js:134:41)
    at Socket.e.on.e (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:14:1123224)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -0:28.1.0 serial-plotter:toggle (input.hidden-input)
```

### Non-Core Packages

```
pymakr 1.5.6 
serial-plotter 0.1.8 
```

**Comment by agent-r** [comment]
Your arduino sketch does not send a propper json string containing your data. Please use the library from https://github.com/devinaconley/arduino-plotter to send the data (or send your data via serial using a corresponding syntax).
Please let me know if that works.
